/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuickRouteImport } from './routes/quick'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as FixedCostsRouteImport } from './routes/fixed-costs'
import { Route as IndexRouteImport } from './routes/index'

const QuickRoute = QuickRouteImport.update({
  id: '/quick',
  path: '/quick',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const FixedCostsRoute = FixedCostsRouteImport.update({
  id: '/fixed-costs',
  path: '/fixed-costs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fixed-costs': typeof FixedCostsRoute
  '/products': typeof ProductsRoute
  '/quick': typeof QuickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fixed-costs': typeof FixedCostsRoute
  '/products': typeof ProductsRoute
  '/quick': typeof QuickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fixed-costs': typeof FixedCostsRoute
  '/products': typeof ProductsRoute
  '/quick': typeof QuickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fixed-costs' | '/products' | '/quick'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fixed-costs' | '/products' | '/quick'
  id: '__root__' | '/' | '/fixed-costs' | '/products' | '/quick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FixedCostsRoute: typeof FixedCostsRoute
  ProductsRoute: typeof ProductsRoute
  QuickRoute: typeof QuickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quick': {
      id: '/quick'
      path: '/quick'
      fullPath: '/quick'
      preLoaderRoute: typeof QuickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixed-costs': {
      id: '/fixed-costs'
      path: '/fixed-costs'
      fullPath: '/fixed-costs'
      preLoaderRoute: typeof FixedCostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FixedCostsRoute: FixedCostsRoute,
  ProductsRoute: ProductsRoute,
  QuickRoute: QuickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
