/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FixedCostsRouteImport } from './routes/fixed-costs'
import { Route as IndexRouteImport } from './routes/index'

const FixedCostsRoute = FixedCostsRouteImport.update({
  id: '/fixed-costs',
  path: '/fixed-costs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fixed-costs': typeof FixedCostsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fixed-costs': typeof FixedCostsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fixed-costs': typeof FixedCostsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fixed-costs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fixed-costs'
  id: '__root__' | '/' | '/fixed-costs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FixedCostsRoute: typeof FixedCostsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/fixed-costs': {
      id: '/fixed-costs'
      path: '/fixed-costs'
      fullPath: '/fixed-costs'
      preLoaderRoute: typeof FixedCostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FixedCostsRoute: FixedCostsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
